- name: Ping test container
  ping:
- name: Install Apache
  apt:
    name: apache2
    state: present
  become: true

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: true
- name: Create test user
  user:
    name: ansibletest
    shell: /bin/bash
    state: present
- name: Copy test page
  copy:
    dest: /var/www/html/index.html
    content: "<h1>Hello from Ansible</h1>"
    owner: www-data
    group: www-data
    mode: '0644'
- name: Install htop
  apt:
    name: htop
    state: present
