---
- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart passgen
  systemd:
    name: passgen
    state: restarted

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
